[routers]
R1 ansible_host=192.168.106.128

[routers:vars]
ansible_user=admin
ansible_password=admin
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
ansible_network_cli_ssh_type=paramiko
ansible_host_key_checking=False
